#' Gather chroma vectors
#'
#' These functions gather chroma or timbre vectors into long format for
#' Computational Musicology, as generated by
#' \code{\link{get_tidy_audio_analysis}}.
#'
#' @param dat Data frame with a \code{pitches} or \code{timbre} column.
#'
#' @importFrom magrittr %>%
#' @export
#'
#' @examples
#' library(tidyverse)
#' get_tidy_audio_analysis('6IQILcYkN2S2eSu5IHoPEH') %>%
#'     select(segments) %>% unnest(segments) %>%
#'     compmus_gather_chroma
#'
#' get_tidy_audio_analysis('5ZLkc5RY1NM4FtGWEd6HOE') %>%
#'     select(segments) %>% unnest(segments) %>%
#'     compmus_gather_timbre
compmus_gather_chroma <- function(dat)
{
    dat %>%
        dplyr::mutate(pitches = purrr::map(pitches, dplyr::bind_rows)) %>%
        tidyr::unnest(pitches) %>%
        tidyr::gather('pitch_class', 'value', C:B) %>%
        dplyr::mutate(pitch_class = forcats::fct_shift(factor(pitch_class), 3))
}

#' @describeIn compmus_gather_chroma Gather timbre vectors
#' @importFrom magrittr %>%
#' @export
compmus_gather_timbre <- function(dat)
{
    dat %>%
        dplyr::mutate(timbre = purrr::map(timbre, dplyr::bind_rows)) %>%
        tidyr::unnest(timbre) %>%
        tidyr::gather('basis', 'value', c01:c12)
}
